---
title: "Assessing Effect Existence: The Quest for a Bayesian p Value"
author: "Dominique Makowski"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: yes
  md_document:
    toc: yes
    variant: markdown_github
  pdf_document:
    toc: yes
tags:
- r
- psychology
- neuroscience
- neuropsychology
- bayesian
- p value
layout: post
---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(knitr)
```



# The data



```{r fig.align='center', message=FALSE, warning=FALSE, comment=NA, results='hide'}
library(tidyverse)
library(ggplot2)
library(rstanarm)
library(psycho)


df <- psycho::affective %>% 
  select(Tolerating, Adjusting) %>% 
  standardize()

cor.test(df$Adjusting, df$Tolerating)

ggplot(df, aes(x=Adjusting, y=Tolerating)) +
  geom_point() +
  geom_smooth()


```



```{r echo=FALSE, message=FALSE, warning=FALSE, results='markup'}
fit <- rstanarm::stan_glm(Adjusting ~ Tolerating, 
                          data=df,
                          seed=666,
                          chains=2,
                          iter=1000)
summary(analyze(fit, effsize=TRUE, bayes_factor = TRUE, overlap = TRUE))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, results='markup'}
results <- power_analysis(fit, n_max = 50, n_min=5, step=1, n_batch=100, CI=90, effsize=TRUE, bayes_factor = TRUE, overlap=TRUE)
saveRDS(results, file="Bayesian_p_Value_Data_50.RData")

results <- power_analysis(fit, n_max = 150, n_min=51, step=1, n_batch=100, CI=90, effsize=TRUE, bayes_factor = TRUE, overlap=TRUE)
saveRDS(results, file="Bayesian_p_Value_Data_150.RData")

results <- power_analysis(fit, n_max = 300, n_min=151, step=1, n_batch=100, CI=90, effsize=TRUE, bayes_factor = TRUE, overlap=TRUE)
saveRDS(results, file="Bayesian_p_Value_Data_300.RData")

results <- power_analysis(fit, n_max = 500, n_min=301, step=1, n_batch=100, CI=90, effsize=TRUE, bayes_factor = TRUE, overlap=TRUE)
saveRDS(results, file="Bayesian_p_Value_Data_500.RData")

results <- power_analysis(fit, n_max = 800, n_min=501, step=1, n_batch=100, CI=90, effsize=TRUE, bayes_factor = TRUE, overlap=TRUE)
saveRDS(results, file="Bayesian_p_Value_Data_800.RData")

results <- power_analysis(fit, n_max = 1251, n_min=801, step=1, n_batch=100, CI=90, effsize=TRUE, bayes_factor = TRUE, overlap=TRUE)
saveRDS(results, file="Bayesian_p_Value_Data_1251.RData")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, results='markup'}
results %>%
  filter(Variable=="Tolerating") %>%
  select(n, MPE, Overlap) %>%
  mutate(Overlap = 100-Overlap) %>%
  group_by(n) %>%
  summarise(MPE_median = median(MPE),
            MPE_lower = psycho::hdi(MPE, prob = 0.8)$values$HDImin,
            MPE_higher = psycho::hdi(MPE, prob = 0.8)$values$HDImax,
            OC_median = median(Overlap),
            OC_lower = psycho::hdi(Overlap, prob = 0.8)$values$HDImin,
            OC_higher = psycho::hdi(Overlap, prob = 0.8)$values$HDImax) %>%
  ggplot(aes(x=n)) +
  geom_line(aes(y=MPE_median)) +
  geom_ribbon(aes(ymin=MPE_lower, ymax=MPE_higher), alpha=0.2) +
  geom_line(aes(y=OC_median), color="blue") +
  geom_ribbon(aes(ymin=OC_lower, ymax=OC_higher), alpha=0.2, fill="blue") +
  theme_bw() +
  ylab("Overlap") +
  xlab("Sample size")

results %>%
  filter(Variable=="Tolerating") %>%
  select(n, MPE, Overlap) %>%
  ggplot(aes(x=MPE, y=Overlap)) +
  geom_point() +
  geom_smooth(method="lm", formula=y~poly(x, 2))

```



# Credits

This package helped you? Don't forget to cite the various packages you used :)

You can cite `psycho` as follows:

- Makowski, (2018). *The psycho Package: an Efficient and Publishing-Oriented Workflow for Psychological Science*. Journal of Open Source Software, 3(22), 470. https://doi.org/10.21105/joss.00470
